CREATE TABLE STATS
(
    STAT_ID   INT(11) AUTO_INCREMENT,
    STAT_DATE DATETIME    NOT NULL,
    STAT      VARCHAR(20) NOT NULL,
    VALUE     INT(11),
    PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT (NUMBER_BESTSELLERS) AS
SELECT COUNT(*)
FROM books
WHERE BESTSELLER = TRUE;


USE KODILLA_COURSE;

CREATE EVENT UPDATE_BESTSELLERS
    ON SCHEDULE EVERY 1 MINUTE
    DO
    BEGIN
        DECLARE COUNTER INT;
        CALL UpdateBestsellers();
        SELECT NUMBER_BESTSELLERS FROM BESTSELLERS_COUNT INTO COUNTER;
        INSERT INTO STATS(STAT_DATE, STAT, VALUE)
        VALUES (CURTIME(), 'BESTSELLERS', COUNTER);
    END;
